apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-udp-shenzhen
  namespace: infra
spec:
  selector:
    matchLabels:
      app: test-udp-shenzhen
  replicas: 1
  template:
    metadata:
      labels:
        app: test-udp-shenzhen
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - sz
      containers:
        - name: test-udp
          image: hub.autox.ai/infra/xremote/test-udp-server:1.0.0
          ports:
            - name: server
              containerPort: 3333
              protocol: UDP
              hostPort: 3333
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["-c", "/opt/udp_server/udp_server"]
